### PR TITLE
This sets up some groundwork to send additional parameters to cloudapi.

### PR DESCRIPTION
**Pull request by pccowboy**
This branch by itself does not break anything.  But, if you want breakage,
pull https://github.com/pccowboy/sdc-cloudapi, branch delegate_dataset.

### CODE REVIEW

**Comment by trentm** [comment]
@pccowboy  Why these changes? Specifying VM metadata with `triton create` is already available with these options:

```
    -m DATA, --metadata=DATA
                Add metadata when creating the instance. Metadata are key/value
                pairs available on the instance API object as the "metadata"
                field, and inside the instance via the "mdata-*" commands. DATA
                is one of: a "key=value" string (bool and numeric "value" are
                converted to that type), a JSON object (if first char is "{"),
                or a "@FILE" to have metadata be loaded from FILE. This option
                can be used multiple times.
    -M KEY=FILE, --metadata-file=KEY=FILE
                Set a metadata key KEY from the contents of FILE.
    --script=FILE
                Load a file to be used for the "user-script" metadata key. In
                Joyent-provided images, the user-script is run at every boot of
                the instance. This is a shortcut for `-M user-script=FILE`.
```

unless I've missed something.

**Comment by pccowboy** [comment]
The options you mention are for metadata.  Unless I missed something, they are limited to the metadata object only.

The changes here and in my cloudapi branch allow you to add parameters to the top-level VM object using triton, which you can only do with vmapi currently.

The primary reason is to allow an operator to easily enable a feature via triton, something like 'delegated_dataset', which is a top-level parameter, not metadata.

https://docs.joyent.com/private-cloud/instances/delegated-data-sets explains one feature this PR enables.

https://www.mail-archive.com/smartos-discuss@lists.smartos.org/msg01751.html explains a bit why I added it to 'triton create'.

**Comment by trentm** [comment]
@pccowboy But `triton` only talks to cloudapi, which doesn't expose all the attributes that `vmadm create` and hence VMAPI's CreateVm support. The only attributes supported are those for cloudapi's CreateMachine: https://apidocs.joyent.com/cloudapi/#CreateMachine

**Comment by pccowboy** [comment]
@trentm I refer you to the comment that accompanied this PR, copied here:

This branch by itself does not break anything. But, if you want breakage,
pull https://github.com/pccowboy/sdc-cloudapi, branch delegate_dataset.

If you check out that companion PR, you will see that indeed, cloudapi can be made to expose additional attributes, such as delegate_dataset.

**Comment by cburroughs** [comment]
HI @pccowboy.  The [CONTRIBUTING](https://github.com/joyent/triton/blob/master/CONTRIBUTING.md) guidelines for this project have changed since you started you work and the project is now longer using pull requests.  If this is something you are still working on please feel free to send a patch to [Gerrit](https://cr.joyent.us).

**Pull request closed without merging**
